log:
  pages:
    - 
      title:
      pageTimings:
        onContentLoad:
        onLoad:
  entries:
    - 
      _priority:
      _resourceType:
      request:
        method:
        url:
        httpVersion:
        headersSize:
        bodySize:
      response:
        status:
        content:
          size:
          mimeType:
        headersSize:
        bodySize:
        _transferSize:
      time:
      timings:
        blocked:
        dns:
        ssl:
        connect:
        send:
        wait:
        receive:
        _blocked_queueing: