name: npm release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        always-auth: true
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn
    - name: publish
      run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc && yarn publish  --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
